Repository gardener/gardener-extension-shoot-rsyslog-relp, pull requests merged in 2023-10, with the labels that each got.

#18 Fix development documentation typo
  docs/development/getting-started.md
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#19 Adds PriorityClass to daemonsets' pods deployed in the shoot cluster
  charts/internal/rsyslog-relp-configuration-cleaner/templates/daemonset.yaml
  charts/internal/rsyslog-relp-configurator/templates/daemonset.yaml
  test/integration/controller/lifecycle/lifecycle_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, needs/cherry-pick, size/xs

#22 skaffold: Rebuild when there are changes to `go:embed` files
  Makefile
  hack/check-skaffold-deps.sh
  skaffold.yaml
Labels: area/dev-productivity, kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m, cla: yes

#14 Introduce the use of central manifest
  .docforge/manifest.yaml
  Makefile
Labels: area/documentation, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/xs, cla: yes

#28 Removes the `healthcheck` controller
  Makefile
  charts/gardener-extension-shoot-rsyslog-relp/templates/deployment.yaml
  charts/gardener-extension-shoot-rsyslog-relp/values.yaml
  cmd/gardener-extension-shoot-rsyslog-relp/app/app.go
  cmd/gardener-extension-shoot-rsyslog-relp/app/options.go
  example/controller-registration.yaml
  hack/api-reference/config.json
  hack/api-reference/config.md
  hack/api-reference/rsyslog.json
  hack/update-codegen.sh
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/cmd/rsyslogrelp/options.go
  pkg/controller/healthcheck/add.go
  pkg/controller/lifecycle/add.go
  skaffold.yaml
  vendor/github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1/doc.go
  vendor/github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1/types.go
  vendor/github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/general/daemonset.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/general/deployment.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/general/managed_resource.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/general/statefulsets.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/healthcheck_actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/inject.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/message_util.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: kind/api-change, kind/cleanup, reviewed/lgtm, needs/ok-to-test, size/m, cla: yes
