Repository gardener/gardener-extension-shoot-rsyslog-relp, pull requests merged in 2024-12, with the labels that each got.

#201 Remove `pkg/controller/config`
  pkg/cmd/rsyslogrelp/options.go
  pkg/controller/config/config.go
  pkg/controller/lifecycle/add.go
  skaffold.yaml
Labels: area/quality, kind/cleanup, size/S, cla: yes, lgtm, approved

#209 Make decoding of `Raw` to configs consistent
  pkg/admission/validator/shoot.go
  pkg/cmd/rsyslogrelp/options.go
  pkg/controller/lifecycle/actuator.go
  pkg/webhook/operatingsystemconfig/auditd.go
  pkg/webhook/operatingsystemconfig/ensurer.go
Labels: area/quality, kind/enhancement, size/M, cla: yes, lgtm, approved

#211 Remove memory resource limits
  charts/gardener-extension-shoot-rsyslog-relp-admission/values.yaml
  charts/gardener-extension-shoot-rsyslog-relp/values.yaml
  example/controller-registration.yaml
Labels: area/auto-scaling, kind/enhancement, size/XS, cla: yes, lgtm, approved
