Repository gardener/gardener-extension-shoot-rsyslog-relp, pull requests merged in 2024-02, with the labels that each got.

#63 Fix minor typo
  README.md
Labels: kind/cleanup, reviewed/lgtm, needs/ok-to-test, size/xs, cla: yes

#62 Do not use a fake REUSE badge
  README.md
Labels: kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs, cla: yes

#61 Clean up sed usage after ControllerRegistration generation
  charts/gardener-extension-shoot-rsyslog-relp/doc.go
  example/controller-registration.yaml
Labels: kind/cleanup, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs, cla: yes

#68 Add `OWNERS` and `OWNERS_ALIASES` files
  OWNERS
  OWNERS_ALIASES
Labels: kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs, cla: yes

#67 Update plutono dashboard tags
  pkg/constants/constants.go
  pkg/controller/lifecycle/dashboard_config.go
Labels: kind/cleanup, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs, cla: yes

#71 Make repository `reuse` compliant
  .reuse/dep5
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/role-binding.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/role.yaml
  pkg/webhook/operatingsystemconfig/resources/auditrules/00-base-config.rules
  pkg/webhook/operatingsystemconfig/resources/auditrules/10-privilege-escalation.rules
  pkg/webhook/operatingsystemconfig/resources/auditrules/11-privileged-special.rules
  pkg/webhook/operatingsystemconfig/resources/auditrules/12-system-integrity.rules
  pkg/webhook/operatingsystemconfig/resources/templates/60-audit.conf.tpl
  pkg/webhook/operatingsystemconfig/resources/templates/scripts/configure-rsyslog.tpl.sh
  pkg/webhook/operatingsystemconfig/resources/templates/scripts/process-rsyslog-pstats.tpl.sh
  pkg/webhook/operatingsystemconfig/testdata/00-base-config.rules
  pkg/webhook/operatingsystemconfig/testdata/10-privilege-escalation.rules
  pkg/webhook/operatingsystemconfig/testdata/11-privileged-special.rules
  pkg/webhook/operatingsystemconfig/testdata/12-system-integrity.rules
  pkg/webhook/operatingsystemconfig/testdata/60-audit-with-tls.conf
  pkg/webhook/operatingsystemconfig/testdata/60-audit.conf
  pkg/webhook/operatingsystemconfig/testdata/configure-rsyslog.sh
  pkg/webhook/operatingsystemconfig/testdata/process-rsyslog-pstats.sh
Labels: kind/enhancement, reviewed/ok-to-test, needs/ok-to-test, size/M, cla: yes, lgtm, approved
