Repository gardener/gardener-extension-shoot-rsyslog-relp, pull requests merged in 2025-02, with the labels that each got.

#226 Forbid privilege escalation for containers
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-shoot-rsyslog-relp/templates/deployment.yaml
  example/controller-registration.yaml
  example/local/charts/rsyslog-relp-echo-server/templates/deployment.yaml
  pkg/component/rsyslogrelpconfigcleaner/rsyslog_relp_config_cleaner.go
  test/integration/controller/lifecycle/lifecycle_test.go
Labels: area/compliance, area/security, kind/enhancement, lifecycle/stale, size/S, cla: yes, lgtm, approved

#228 Prepare for deployment of admission controller by gardener-operator
  .ci/pipeline_definitions
  charts/gardener-extension-shoot-rsyslog-relp-admission/Chart.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/application/.helmignore
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/application/templates/_helpers.tpl
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/application/templates/cluster-role-binding.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/application/values.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/.helmignore
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/_helpers.tpl
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/secret-kubeconfig.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/service.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/values.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/templates/_helpers.tpl
  charts/gardener-extension-shoot-rsyslog-relp-admission/values.yaml
  cmd/gardener-extension-shoot-rsyslog-relp-admission/app/app.go
  skaffold.yaml
Labels: area/control-plane, kind/enhancement, size/L, cla: yes, lgtm, approved

#236 Fix tagging of extension image for remote dev setup
  Makefile
Labels: area/dev-productivity, kind/bug, size/XS, cla: yes, lgtm, approved

#239 Fixes reuse compliance
  .reuse/dep5
Labels: area/compliance, kind/bug, size/XS, cla: yes, lgtm, approved

#235 Drop `shoot` label from `TestSuiteShootRsyslogRelpSerial.yaml` test definition
  .test-defs/TestSuiteShootRsyslogRelpSerial.yaml
Labels: area/testing, kind/enhancement, size/XS, cla: yes, lgtm, approved
