Repository gardener/gardener-extension-shoot-rsyslog-relp, pull requests merged in 2025-05, with the labels that each got.

#266 Reduce RBAC permissions
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/application/templates/cluster-role.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/role.yaml
  charts/gardener-extension-shoot-rsyslog-relp/templates/clusterrole.yaml
  charts/gardener-extension-shoot-rsyslog-relp/templates/role.yaml
  cmd/gardener-extension-shoot-rsyslog-relp-admission/app/app.go
  example/controller-registration.yaml
Labels: area/security, kind/enhancement, size/L, cla: yes, lgtm, approved

#273 tm tests: Add expectation framework's Shoot client not to be nil
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
Labels: area/testing, kind/enhancement, size/S, cla: yes, lgtm, approved

#259 Add webhook integration test
  pkg/webhook/operatingsystemconfig/ensurer_test.go
  pkg/webhook/operatingsystemconfig/webhooktest/testdata/00-base-config.rules
  pkg/webhook/operatingsystemconfig/webhooktest/testdata/10-privilege-escalation.rules
  pkg/webhook/operatingsystemconfig/webhooktest/testdata/11-privileged-special.rules
  pkg/webhook/operatingsystemconfig/webhooktest/testdata/12-system-integrity.rules
  pkg/webhook/operatingsystemconfig/webhooktest/testdata/60-audit-with-tls.conf
  pkg/webhook/operatingsystemconfig/webhooktest/testdata/60-audit.conf
  pkg/webhook/operatingsystemconfig/webhooktest/testdata/configure-rsyslog.sh
  pkg/webhook/operatingsystemconfig/webhooktest/testdata/process-rsyslog-pstats.sh
  pkg/webhook/operatingsystemconfig/webhooktest/testdata/rsyslog-config-simple.conf.tpl
  pkg/webhook/operatingsystemconfig/webhooktest/webhooktest.go
  test/integration/controller/lifecycle/lifecycle_suite_test.go
  test/integration/resources/crd-extensions.gardener.cloud_clusters.yaml
  test/integration/resources/crd-extensions.gardener.cloud_extensions.yaml
  test/integration/resources/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  test/integration/resources/crd-monitoring.coreos.com_prometheusrules.yaml
  test/integration/resources/crd-monitoring.coreos.com_scrapeconfigs.yaml
  test/integration/resources/crd-resources.gardener.cloud_managedresources.yaml
  test/integration/resources/doc.go
  test/integration/webhook/operatingsystemconfig/operatingsystemconfig_suite_test.go
  test/integration/webhook/operatingsystemconfig/operatingsystemconfig_test.go
Labels: area/testing, kind/test, cla: yes, lgtm, approved, size/XXL
