Repository gardener/gardener-extension-shoot-rsyslog-relp, pull requests merged in 2025-04, with the labels that each got.

#260 Change the imageVectorOverwrite value type from string to object
  charts/gardener-extension-shoot-rsyslog-relp/templates/configmap-imagevector-overwrite.yaml
  charts/gardener-extension-shoot-rsyslog-relp/values.yaml
  example/controller-registration.yaml
Labels: area/ops-productivity, area/usability, kind/enhancement, size/S, cla: yes, lgtm, approved

#262 Execute `augenrules --load` only when necessary
  pkg/webhook/operatingsystemconfig/resources/templates/scripts/configure-rsyslog.tpl.sh
  pkg/webhook/operatingsystemconfig/testdata/configure-rsyslog.sh
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#261 Remove `shoot` and `beta` labels from test defs
  .test-defs/TestSuiteShootRsyslogRelpSerial.yaml
Labels: kind/cleanup, size/XS, cla: yes, lgtm, approved
