Repository gardener/gardener-extension-shoot-rsyslog-relp, pull requests merged in 2025-03, with the labels that each got.

#190 Drop support for Shoots with Kubernetes version <= 1.26
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/service.yaml
  charts/gardener-extension-shoot-rsyslog-relp/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
Labels: kind/cleanup, size/S, cla: yes, lgtm, approved

#242 local setup: Fix issue where ControllerDeployment image is not updated if the images are already cached ones
  Makefile
  charts/gardener-extension-shoot-rsyslog-relp/templates/_helpers.tpl
  charts/gardener-extension-shoot-rsyslog-relp/values.yaml
  example/controller-registration.yaml
  hack/generate-kustomize-patch-controllerdeployment-shoot-rsyslog-relp.sh
  local-setup/.gitignore
  local-setup/kustomization.yaml
  skaffold.yaml
Labels: area/dev-productivity, kind/bug, size/M, cla: yes, lgtm, approved

#248 Increase parallel execution of e2e tests from 2 to 3
  Makefile
Labels: area/testing, kind/enhancement, size/XS, cla: yes, lgtm, approved

#250 Bump github.com/gardener/gardener from 1.113.0 to 1.114.1
  go.mod
  go.sum
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved

#251 Bring back tm beta labels so that tests can be properly GAed
  .test-defs/TestSuiteShootRsyslogRelpSerial.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#224 Use ServiceTrafficDistribution to make Services topology-aware when runtime Kubernetes >= 1.31
  charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime/templates/service.yaml
Labels: area/high-availability, area/networking, kind/enhancement, size/XS, cla: yes, lgtm, approved

#243 Enable filtering on log message content
  docs/usage/configuration.md
  example/extension/extension-config-patch.yaml.tmpl
  example/shoot.yaml
  hack/api-reference/rsyslog.md
  hack/test-e2e-local.sh
  pkg/apis/rsyslog/types_rsyslog.go
  pkg/apis/rsyslog/v1alpha1/types_rsyslog.go
  pkg/apis/rsyslog/v1alpha1/zz_generated.conversion.go
  pkg/apis/rsyslog/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/rsyslog/validation/rsyslog_relp.go
  pkg/apis/rsyslog/validation/validation_test.go
  pkg/apis/rsyslog/zz_generated.deepcopy.go
  pkg/webhook/operatingsystemconfig/ensurer_test.go
  pkg/webhook/operatingsystemconfig/rsyslog.go
  pkg/webhook/operatingsystemconfig/testdata/60-audit-with-tls.conf
  pkg/webhook/operatingsystemconfig/testdata/60-audit.conf
  test/common/configuration.go
  test/common/verifier.go
  test/e2e/create_enable_disable_delete.go
  test/integration/controller/lifecycle/lifecycle_test.go
  test/testmachinery/shoot/enable_disable_test.go
Labels: area/dev-productivity, kind/enhancement, size/L, cla: yes, lgtm, approved

#249 Explicitly disable audit configuration for local setup and e2e tests
  example/shoot.yaml
  test/e2e/create_enable_disable_delete.go
  test/e2e/create_enable_force_delete.go
  test/e2e/create_enabled_hibernate_reconcile_delete_test.go
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved

#254 Add message content filtering documentation to configuration.md
  docs/usage/configuration.md
Labels: area/documentation, kind/enhancement, size/XS, cla: yes, lgtm, approved
