Repository gardener/gardener-extension-shoot-rsyslog-relp, pull requests merged in 2025-09, with the labels that each got.

#304 Clean up stale target dependency to `yaml2json`
  Makefile
Labels: area/dev-productivity, kind/cleanup, size/XS, cla: yes, lgtm, approved

#301 Add generation for `Extension` example
  Makefile
  REUSE.toml
  example/doc.go
  example/extension.yaml
  example/extension/.gitignore
  example/extension/registration/base/extension.yaml
  example/extension/registration/base/kustomization.yaml
  example/extension/registration/extension-patch.yaml
  example/extension/registration/kustomization.yaml
Labels: area/ops-productivity, area/ipcei, kind/enhancement, size/M, cla: yes, lgtm, approved

#302 Add source repo for alpine image
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#313 Fix roles in `ScrapeConfig`s
  pkg/controller/lifecycle/monitoring.go
Labels: area/networking, kind/bug, size/XS, cla: yes, lgtm, approved
